-- MySQL Script generated by MySQL Workbench
-- Tue Jan 17 10:29:06 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tax_service
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tax_service` ;

-- -----------------------------------------------------
-- Schema tax_service
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tax_service` DEFAULT CHARACTER SET utf8 ;
USE `tax_service` ;

-- -----------------------------------------------------
-- Table `tax_service`.`report_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tax_service`.`report_status` ;

CREATE TABLE IF NOT EXISTS `tax_service`.`report_status` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tax_service`.`company_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tax_service`.`company_type` ;

CREATE TABLE IF NOT EXISTS `tax_service`.`company_type` (
  `id` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `type_UNIQUE` (`type` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tax_service`.`report_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tax_service`.`report_type` ;

CREATE TABLE IF NOT EXISTS `tax_service`.`report_type` (
  `id` INT NOT NULL,
  `company_type_id` INT NOT NULL,
  `report_type` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_report_type_company_type1_idx` (`company_type_id` ASC) VISIBLE,
  UNIQUE INDEX `report_type_UNIQUE` (`report_type` ASC) VISIBLE,
  CONSTRAINT `fk_report_type_company_type1`
    FOREIGN KEY (`company_type_id`)
    REFERENCES `tax_service`.`company_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tax_service`.`adress`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tax_service`.`adress` ;

CREATE TABLE IF NOT EXISTS `tax_service`.`adress` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `country` VARCHAR(100) NOT NULL DEFAULT 'Ukraine',
  `state` VARCHAR(100) NOT NULL,
  `city` VARCHAR(100) NOT NULL,
  `street` VARCHAR(100) NOT NULL,
  `building` INT NOT NULL,
  `building_letter` VARCHAR(2) NULL,
  `office` INT NOT NULL,
  `office_letter` VARCHAR(2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tax_service`.`company_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tax_service`.`company_data` ;

CREATE TABLE IF NOT EXISTS `tax_service`.`company_data` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_type_id` INT NOT NULL,
  `name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `inn_edrpou` VARCHAR(10) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `adress_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_company_data_company_type1_idx` (`company_type_id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  UNIQUE INDEX `inn_edrpou_UNIQUE` (`inn_edrpou` ASC) VISIBLE,
  INDEX `fk_company_data_adress1_idx` (`adress_id` ASC) VISIBLE,
  CONSTRAINT `fk_company_data_company_type1`
    FOREIGN KEY (`company_type_id`)
    REFERENCES `tax_service`.`company_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_company_data_adress1`
    FOREIGN KEY (`adress_id`)
    REFERENCES `tax_service`.`adress` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tax_service`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tax_service`.`role` ;

CREATE TABLE IF NOT EXISTS `tax_service`.`role` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tax_service`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tax_service`.`user` ;

CREATE TABLE IF NOT EXISTS `tax_service`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `password` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' BINARY NOT NULL,
  `create_time` DATETIME GENERATED ALWAYS AS (),
  `role_id` INT NOT NULL,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  INDEX `fk_user_role1_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `tax_service`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tax_service`.`report`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tax_service`.`report` ;

CREATE TABLE IF NOT EXISTS `tax_service`.`report` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `report_type_id` INT NOT NULL,
  `financial_income` DOUBLE NOT NULL,
  `tax_amount` DOUBLE NOT NULL,
  `description` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL,
  `comment` LONGTEXT CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL,
  `date_create` DATETIME GENERATED ALWAYS AS (),
  `date_last_edit` DATETIME NOT NULL,
  `status_id` INT NOT NULL,
  `company_data_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `report_body` BLOB NOT NULL,
  PRIMARY KEY (`id`, `status_id`),
  INDEX `fk_receipt_receipt_status1_idx` (`status_id` ASC) VISIBLE,
  INDEX `fk_report_report_type1_idx` (`report_type_id` ASC) VISIBLE,
  INDEX `fk_report_company_data1_idx` (`company_data_id` ASC) VISIBLE,
  INDEX `fk_report_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_receipt_receipt_status1`
    FOREIGN KEY (`status_id`)
    REFERENCES `tax_service`.`report_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_report_report_type1`
    FOREIGN KEY (`report_type_id`)
    REFERENCES `tax_service`.`report_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_report_company_data1`
    FOREIGN KEY (`company_data_id`)
    REFERENCES `tax_service`.`company_data` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_report_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `tax_service`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tax_service`.`user_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tax_service`.`user_details` ;

CREATE TABLE IF NOT EXISTS `tax_service`.`user_details` (
  `user_id` INT NOT NULL,
  `last_accessed_id` VARCHAR(45) NULL,
  INDEX `fk_user_details_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_details_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `tax_service`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tax_service`.`user_has_company_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tax_service`.`user_has_company_data` ;

CREATE TABLE IF NOT EXISTS `tax_service`.`user_has_company_data` (
  `user_id` INT NOT NULL,
  `company_data_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `company_data_id`),
  INDEX `fk_user_has_company_data_company_data1_idx` (`company_data_id` ASC) VISIBLE,
  INDEX `fk_user_has_company_data_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_company_data_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `tax_service`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_company_data_company_data1`
    FOREIGN KEY (`company_data_id`)
    REFERENCES `tax_service`.`company_data` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
